export const FETCH_SECRET_REQUEST = "FETCH_SECRET_REQUEST";
export const FETCH_SECRET_SUCCESS = "FETCH_SECRET_SUCCESS";
export const FETCH_SECRET_FAILURE = "FETCH_SECRET_FAILURE";
export const CREATE_SECRET_REQUEST = "CREATE_SECRET_REQUEST";
export const CREATE_SECRET_SUCCESS = "CREATE_SECRET_SUCCESS";
export const CREATE_SECRET_FAILURE = "CREATE_SECRET_FAILURE";
export const RESET_ERROR = "RESET_ERROR";
